version: '3'

services:
   #  app:
   #     build: ./

   #     container_name: 'botanik-bot'
   #     image: botanik-bot
   #     restart: always

   #     links:
   #        - database:database

   #     environment:
   #        - DATABASE_HOST=database
   #        - DATABASE_PORT=3306
   #        - BOT_TOKEN=6598308741:AAFfE8VWqxbq4GRgxypnXbeOkgalp9_UX0E
   #        - IS_BACKUPS=true

   database:
      container_name: 'botanik-database'
      image: mysql:8.0
      restart: always
      environment:
         MYSQL_DATABASE: 'main_database'
         MYSQL_USER: 'MainUser'
         MYSQL_PASSWORD: 'dkfjsdofnsofnmno5j84584nknvkIDJFIDOFJODS&&&***&(hjhdfkldf'
         MYSQL_ROOT_PASSWORD: 'root'
         LANG: C.UTF-8
      ports:
         - '3306:3306'
      expose:
         - '3306'
      volumes:
         - D:/Progects/BotanikBot/system/database:/var/lib/mysql
      command:
         [
            'mysqld',
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci',
         ]
